### ISSUE TITLE
Add option to use multiple accounts

### ISSUE THREAD

**Issue by coditva** [OSDLabs/BitsnetLogin#14]

**Comment by kaivalyar** [comment]
This could be a very nice addition!

**Comment by coditva** [comment]
@kaivalyar ikr! But how do you think it should be done? like, should the script store credentials for multiple accounts and choose one? The captive portal does not allow multiple logins for same IP, and possibly same MAC address...

**Comment by kaivalyar** [comment]
Store multiple accounts, in a specified order of preference:
try the first - if it works, great!
else if data exceeded / too many simultaneous logins, try the next
... and so on.

what say?

**Comment by coditva** [comment]
Exactly what I had in mind! :grin:
